import os
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

# Configure the Gemini API Keys (Using Pro for complex reasoning)
gemini_api_key = os.getenv("GEMINI_API_KEY")
if not gemini_api_key:
    raise ValueError("GEMINI_API_KEY is not set in the environment.")

genai.configure(api_key=gemini_api_key)

# We use the higher-tier Pro model specifically for The Explainability Engine
# as it excels at detailed analytical context blending.
explainability_model = genai.GenerativeModel('gemini-1.5-pro')

async def generate_match_rationale(startup_data: dict, mentor_data: dict, hybrid_score: float, retrieved_context: str) -> str:
    """
    Translates mathematical hybrid scoring back into human-readable intuition.
    Admin users need to understand *why* the AI generated a specific match before 
    they click "Approve". 
    
    Args:
        startup_data: Structure dictionary of the startup's profile
        mentor_data: Structured dictionary of the mentor's profile
        hybrid_score: The calculated final float from the Hybrid Ranker
        retrieved_context: Semantic RAG chunk data to ground the reasoning
        
    Returns:
        str: A 2-3 sentence logical explanation generated by Gemini 1.5 Pro
    """

    
    # We defensively format the extraction of keys to avoid NoneType errors in the prompt
    s_name = startup_data.get("company_name", "the startup")
    s_needs = startup_data.get("company_needs", "Unknown")
    s_ind = startup_data.get("industry", "Unknown")
    
    m_name = mentor_data.get("mentor_name", "the mentor")
    m_exp = mentor_data.get("expertise", "Unknown")
    m_ind = mentor_data.get("industries", "Unknown")
    
    # Strict prompt configuration
    system_prompt = (
        "You are an expert ecosystem matching analyst. Read the startup's needs, the mentor's expertise, "
        "and the retrieved historical ecosystem context. Based on this data and their Hybrid AI Match Score, "
        "write a concise, professional 2-3 sentence explanation of WHY this mentor is highly recommended for this startup. "
        "You MUST explicitly weave the 'Retrieved Ecosystem Context' into your justification to prove it is learning "
        "from the ecosystem. Do not use filler words. Be analytical and specific to their data."
    )
    
    user_context = f"""
    -- MATCH DATA INPUT --
    Hybrid AI Confidence Score: {hybrid_score * 100:.1f}%
    
    STARTUP ({s_name}):
    - Industry: {s_ind}
    - Stated Needs: {s_needs}
    
    MENTOR ({m_name}):
    - Industries/Domain: {m_ind}
    - Expertise: {m_exp}
    
    {retrieved_context}
    
    Draft the rationale below:
    """

    try:
        response = explainability_model.generate_content(
            system_prompt + "\n\n" + user_context
        )
        
        return response.text.strip()
    except Exception as e:
        print(f"Explainability Engine Failure: {str(e)}")
        return "AI analysis unavailable. This match scored highly across structural and semantic baseline metrics."
